// Generated by gencpp from file me212base/gripper.msg
// DO NOT EDIT!


#ifndef ME212BASE_MESSAGE_GRIPPER_H
#define ME212BASE_MESSAGE_GRIPPER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me212base
{
template <class ContainerAllocator>
struct gripper_
{
  typedef gripper_<ContainerAllocator> Type;

  gripper_()
    : task(0)  {
    }
  gripper_(const ContainerAllocator& _alloc)
    : task(0)  {
  (void)_alloc;
    }



   typedef int16_t _task_type;
  _task_type task;




  typedef boost::shared_ptr< ::me212base::gripper_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me212base::gripper_<ContainerAllocator> const> ConstPtr;

}; // struct gripper_

typedef ::me212base::gripper_<std::allocator<void> > gripper;

typedef boost::shared_ptr< ::me212base::gripper > gripperPtr;
typedef boost::shared_ptr< ::me212base::gripper const> gripperConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me212base::gripper_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me212base::gripper_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me212base

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'me212base': ['/home/robot/team2a/catkin_ws/src/me212base/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me212base::gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me212base::gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212base::gripper_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212base::gripper_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212base::gripper_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212base::gripper_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me212base::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4a46e74c396fe49dcc327f0e08dbcb98";
  }

  static const char* value(const ::me212base::gripper_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4a46e74c396fe49dULL;
  static const uint64_t static_value2 = 0xcc327f0e08dbcb98ULL;
};

template<class ContainerAllocator>
struct DataType< ::me212base::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me212base/gripper";
  }

  static const char* value(const ::me212base::gripper_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me212base::gripper_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int16 task\n\
";
  }

  static const char* value(const ::me212base::gripper_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me212base::gripper_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct gripper_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me212base::gripper_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me212base::gripper_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<int16_t>::stream(s, indent + "  ", v.task);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME212BASE_MESSAGE_GRIPPER_H
