joint2_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: joint2
    joint_speed: 0.3
    motor:
        id: 22
        init: 2047
        min: 551
        max: 3621
  
