// Generated by gencpp from file me212cv/DetectObject.msg
// DO NOT EDIT!


#ifndef ME212CV_MESSAGE_DETECTOBJECT_H
#define ME212CV_MESSAGE_DETECTOBJECT_H

#include <ros/service_traits.h>


#include <me212cv/DetectObjectRequest.h>
#include <me212cv/DetectObjectResponse.h>


namespace me212cv
{

struct DetectObject
{

typedef DetectObjectRequest Request;
typedef DetectObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DetectObject
} // namespace me212cv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::me212cv::DetectObject > {
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::me212cv::DetectObject&) { return value(); }
};

template<>
struct DataType< ::me212cv::DetectObject > {
  static const char* value()
  {
    return "me212cv/DetectObject";
  }

  static const char* value(const ::me212cv::DetectObject&) { return value(); }
};


// service_traits::MD5Sum< ::me212cv::DetectObjectRequest> should match 
// service_traits::MD5Sum< ::me212cv::DetectObject > 
template<>
struct MD5Sum< ::me212cv::DetectObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::me212cv::DetectObject >::value();
  }
  static const char* value(const ::me212cv::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::me212cv::DetectObjectRequest> should match 
// service_traits::DataType< ::me212cv::DetectObject > 
template<>
struct DataType< ::me212cv::DetectObjectRequest>
{
  static const char* value()
  {
    return DataType< ::me212cv::DetectObject >::value();
  }
  static const char* value(const ::me212cv::DetectObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::me212cv::DetectObjectResponse> should match 
// service_traits::MD5Sum< ::me212cv::DetectObject > 
template<>
struct MD5Sum< ::me212cv::DetectObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::me212cv::DetectObject >::value();
  }
  static const char* value(const ::me212cv::DetectObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::me212cv::DetectObjectResponse> should match 
// service_traits::DataType< ::me212cv::DetectObject > 
template<>
struct DataType< ::me212cv::DetectObjectResponse>
{
  static const char* value()
  {
    return DataType< ::me212cv::DetectObject >::value();
  }
  static const char* value(const ::me212cv::DetectObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ME212CV_MESSAGE_DETECTOBJECT_H
