// Generated by gencpp from file me212cv/DetectObjectResponse.msg
// DO NOT EDIT!


#ifndef ME212CV_MESSAGE_DETECTOBJECTRESPONSE_H
#define ME212CV_MESSAGE_DETECTOBJECTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace me212cv
{
template <class ContainerAllocator>
struct DetectObjectResponse_
{
  typedef DetectObjectResponse_<ContainerAllocator> Type;

  DetectObjectResponse_()
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
    }
  DetectObjectResponse_(const ContainerAllocator& _alloc)
    : x(0.0)
    , y(0.0)
    , z(0.0)  {
  (void)_alloc;
    }



   typedef float _x_type;
  _x_type x;

   typedef float _y_type;
  _y_type y;

   typedef float _z_type;
  _z_type z;




  typedef boost::shared_ptr< ::me212cv::DetectObjectResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::me212cv::DetectObjectResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectObjectResponse_

typedef ::me212cv::DetectObjectResponse_<std::allocator<void> > DetectObjectResponse;

typedef boost::shared_ptr< ::me212cv::DetectObjectResponse > DetectObjectResponsePtr;
typedef boost::shared_ptr< ::me212cv::DetectObjectResponse const> DetectObjectResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::me212cv::DetectObjectResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::me212cv::DetectObjectResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace me212cv

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::me212cv::DetectObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::me212cv::DetectObjectResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::me212cv::DetectObjectResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cc153912f1453b708d221682bc23d9ac";
  }

  static const char* value(const ::me212cv::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xcc153912f1453b70ULL;
  static const uint64_t static_value2 = 0x8d221682bc23d9acULL;
};

template<class ContainerAllocator>
struct DataType< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "me212cv/DetectObjectResponse";
  }

  static const char* value(const ::me212cv::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 x\n\
float32 y\n\
float32 z\n\
\n\
";
  }

  static const char* value(const ::me212cv::DetectObjectResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DetectObjectResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::me212cv::DetectObjectResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::me212cv::DetectObjectResponse_<ContainerAllocator>& v)
  {
    s << indent << "x: ";
    Printer<float>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<float>::stream(s, indent + "  ", v.y);
    s << indent << "z: ";
    Printer<float>::stream(s, indent + "  ", v.z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ME212CV_MESSAGE_DETECTOBJECTRESPONSE_H
